name = "owned-greeter"
version = "<%= package.version %>"
description = "Simple greeter project that can be owned"
keywords = ["sample", "greeter", "owned"]

[setting.salt]
defaultValue = "owned-greeter"

[contract.Greeter]
artifact = "Greeter"
args = ['0x70997970C51812dc3A010C7d01b50e0d17dc79C8']
salt = "<%= settings.salt %>"

# Call Greeter.setGreeting
# This should fail (unless called with the below address as the signer)
[invoke.setGreeting]
target = ["Greeter"]
func = "setGreeting"
from = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
args = [0, "hello world!"]